### ISSUE TITLE
'redo' without loop block

### ISSUE THREAD

**Issue by ehuelsmann** [FGasper/p5-Protocol-DBus#4]
In https://github.com/FGasper/p5-Protocol-DBus/blob/master/lib/Protocol/DBus/Parser.pm#L36 there's a `redo` statement. Reading http://perldoc.perl.org/functions/redo.html, `redo` can't be used outside of loop blocks. However, I'm not seeing the loop block in the `get_message` sub that this redo statement is part of.

**Comment by FGasper** [comment]
The loop is an anonymous one; it starts at line 26. Are you seeing an error or warning from this?

**Comment by ehuelsmann** [comment]
Nope. I don't. Trying to figure out why I didn't see the signals, I was reading through the code looking for looping constructs. This was one of the places I found a looping keyword, but this one I didn't understand from the surrounding code.
