### ISSUE TITLE
Dependencies aren't pure perl (Socket::MsgHdr)

### ISSUE THREAD

**Issue by ehuelsmann** [FGasper/p5-Protocol-DBus#6]
While it's true that your module is Pure Perl, the Socket::MsgHdr dependency isn't. By itself that's not a problem, however, there doesn't seem to be a Pure Perl fallback.

More precisely, I'm running one of the submitted examples (called `dbus.pl` on my system) through `App::FatPacker` and I'm getting this output:

```plain
 $ fatpack pack dbus.pl > fat-dbus.pl
dbus.pl syntax OK
File /home/ehuelsmannfatlib/perl/5.24.1/auto/Socket/MsgHdr/MsgHdr.so isn't a .pm file - can't pack this -- if you hoped we were going to, things may not be what you expected later
 at /usr/share/perl5/App/FatPacker.pm line 251.
```

**Comment by FGasper** [comment]
I’ve been back and forth on how to represent that. I’ve got a recvmsg implementation pending for Linux::Perl that would alleviate the XS dependency, but of course that will only work in Linux.

For now, though, yes, while P::DBus itself is pure Perl, use of the EXTERNAL authn mechanism requires sendmsg, which isn’t portably implementable without XS.

**Comment by ehuelsmann** [comment]
Ok. Well, I guess DBus itself isn't very portable. So maybe that shouldn't be an issue. My main problem is that I'd really like to generate a binary which I can move from one system to another (all Linux systems) without having to reinstall all the (Perl) dependencies on each system. My current approach is to generate a PAR (pp) binary which I then deploy. I started out with fatpacker, which throws the above warning/error. "pp" (at my instruction) includes the MsgHdr.so file in the resulting binary.

**Comment by FGasper** [comment]
@ehuelsmann Once I’m happier w/ Linux::Perl’s implementation of sendmsg I mean to patch in compatibility so it’ll favor that module if it’s available. That will provide the solution you’re looking for.

**Comment by FGasper** [comment]
@ehuelsmann So, it turns out that Socket::MsgHdr is only needed for unix fd passing, not for passing credentials.

Have a look at the 0.06 trial release, which no longer requires Socket::MsgHdr.

**Comment by ehuelsmann** [comment]
Things work perfectly out of the box with 0.06, no longer requires me to explicitly use Socket::MsgHdr. Thanks!
