### ISSUE TITLE
Inconsistent use of $self->{_paused} between Protocol::DBus::Client::Mojo and ::EventBase

### ISSUE THREAD

**Issue by Corion** [FGasper/p5-Protocol-DBus#9]
When trying Protocol::DBus::Client::Mojo together with Mojo::Reactor::Prima, an inconsistency in the use of
`$self->{_paused}` manifested itself in a crash:

    Mojo::Reactor::Prima: I/O watcher failed: Can't use an undefined value as a SCALAR reference at /home/corion/perl5/lib/perl5/Protocol/DBus/Client/Mojo.pm line 174.

Unfortunately, I can't reproduce this in a smaller, self-contained program yet, but visual inspection of line 174 of `lib/Protocol/DBus/Client/Mojo.pm` resp. the line initializing `$paused_r` shows this:

    my $paused_r = $self->{'_paused'};

This feels wrong since `$paused_r` should be a reference to the `_paused` key and is also used as such. A similiar piece of code in ::EventBase shows use as a reference:

```
sub initialize {
    my ($self) = @_;

    my $paused_sr = \$self->{'_paused'};

    my $dbus = $self->{'db'};
    ...
```

Changing the line to a reference makes the problem go away:

    my $paused_r = \$self->{'_paused'};

But even with that change, in the larger program, the DBus promises never get resolved when the Mojo::Reactor::Prima event loop is used.

The program works with only Mojolicious and DBus alone, but I'm at a loss to see where the Mojo::IOLoop is different from the Mojo::Reactor::Prima, or to understand what special things DBus needs from the io-loop that Prima does not provide.

I've attached a not-so-short self-contained example program to reproduce the problem. The program passes with `$mojo_reactor_prima` set to 0, but fails with `$mojo_reactor_prima` set to 1.

Maybe you have an idea?

[prima-dbus-interaction.pl.txt](https://github.com/FGasper/p5-Protocol-DBus/files/8749532/prima-dbus-interaction.pl.txt)

**Comment by FGasper** [comment]
Hi. I'll try to look at this sometime this week. I've never used Prima though..did you contact M/R/Prima's maintainer?

**Comment by Corion** [comment]
No - that's a good point! I'll pull him in here by mentioning @dk ( https://github.com/dk ) resp. mentioning https://github.com/dk/Mojo-Reactor-Prima

**Comment by dk** [comment]
No idea but since the code was mostly copy-pasta anyway from some other M::R:: module I would guess some internal have changed along the way. This paused thing is not related to Prima, it is Mojo's API, at least. My first shot would be to look at sibling M::R:: modules and see if there are any differences. I shall take a look when time permits but if this is urgent you are welcome to investigate and send a pull request, too

**Comment by FGasper** [comment]
@Corion: See if the fix_mojo_pause branch works for you re the SCALAR exception bug.

If you’ll confirm that I’ll make a new release.

**Comment by FGasper** [comment]
As to the Prima compatibility issue: I suspect it’s some problem with M::R::Prima given that apparently all is well with the stock Reactor implementation. Which Reactors have you tried?

- Select
- Poll
- EV
- … ?

**Comment by Corion** [comment]
Merging my fix in https://github.com/dk/Mojo-Reactor-Prima/pull/1 makes my test program work. I still think that the reference taking in 

    my $paused_r = $self->{'_paused'};

is wrong, but now it doesn't cause anymore harm, so this can be closed!

Thank you both for your insights and prompts!

**Comment by FGasper** [comment]
@Corion Fix coming for that; see my last comment.

**Comment by dk** [comment]
jfyi -- the pull request is applied and 1.02 is released now
